"""add_chat_type

Revision ID: b7141bdc4198
Revises: c28f7ef23b57
Create Date: 2024-01-24 19:13:13.043664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7141bdc4198'
down_revision = 'c28f7ef23b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('type', sa.Enum('private', 'channel', 'group', 'supergroup', name='chattype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'type')
    # ### end Alembic commands ###
